version: 2.1

orbs:
 android: circleci/android@0.2.1


jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      #gradle build
      - run:
          name: gradle build
          command: |
            ./gradlew --console=plain build

      #gradle jacoco
          name: gradle jacoco
          command: |
            ./gradlew --console=plain jacocoTestReport

     # save tests!
      - run:
          name: Save test results
          command: |
            mkdir -p ~/atrifact
            ls -l ./CashSDK/build
            cp -r ./CashSDK/build/reports ~/atrifact;
            cp -r ./CashSDK/build/test-results ~/atrifact;


          when: always
      - store_test_results:
          path: ./CashSDK/build/test-results/testDebugUnitTest
      - store_artifacts:
          path: ~/atrifact